input,icon 样式修改
bsb-mbp/mand-mobile pull request #12
Opened 2019-12-10 13:28 UTC by taiyang1994

2019-12-16 09:49 UTC, HermannLizard requested changes
1. 代码规范，尽快开启编辑器自动检查
2. md-input组件重新起个名
3. 个十百千万那个，搜个更好的解法

2019-12-16 09:49 UTC, HermannLizard commented on components/icon/default-svg-list.js
> +  infoBlue:
不要写一样的代码，尤其是公用的组件库。想办法解决。你的问题是svg中画上色的fill和stroke写死了，导致没有cascade到父级的色值，改成currentColor试试。

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +    ]"
inputEnv编译后类名是什么？类名规范是小写加中划线
以及，bool型的类名更推荐这么写：
:class="{
  'is-active': isInputActive,
  'is-focus': isInputFocus,
  'is-disabled': isDisabled
  'is-input-env': true
}"

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +    <md-icon name="search" id="search-icon" size="xs" style="position:absolute;left:5px"/>
能用ref就别用dom

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +        v-if="align=='center'"
===

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +    <md-icon name="search" id="search-icon" size="xs" style="position:absolute;left:5px"/>
尽量避免行内样式

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +        <md-icon name="search" size="xs" style="padding-right:3px"/><span class="shake">{{placeholder}}</span>
尽量避免行内样式；如果是为兼容性写的hack需要注释说明。

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      if (isIOS) {
如果是改的mand-mobile且改动率小于50%，不需要改原来的代码规范；如果是自己写的，需要保持代码规范，else换行，分号等

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +  },
没有函数体就删了吧

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +    document.querySelector("#search-icon").style.display = "none";
这个md-field-item-control和search-icon的dom是生成的吗？为何不能在模板中用类名或者v-if控制

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      if(this.align == 'center'){
if后面，{前面空格

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      if(this.align == 'center'&& this.isInputEmpty){
同上

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      }, 100);
定时器是为啥，100ms是怎么估出来的

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      }, 200);
同上，200是怎么估出来的

2019-12-16 09:49 UTC, HermannLizard commented on components/input-search/index.vue
> +      this.$el.querySelector('.md-input-item-input').blur();
这里同上，能用ref就别用dom，如果以后改了input的类名，这里就失效了。在vue组件中，组件内部的类名一般不在外部使用，使用就会产生耦合。

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/component.js
> +  'author': 'xuxiaoyan'
这位是？

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/cursor.js
> +/**
这个文件如果没有更改，可以用input-item原目录下的吧

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/demo/index.vue
> +<template>
这个组件名可以再想想，mand-mobile是他们组件库的名字，看起来以前保留的他们的input更应该叫这个名字。但为了方便从didi pr，以前的input还是保留比较好。咱们的可以起个什么 advanced-input 之类的

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +  <fieldset class="md-field" style="background:#fff">
avoid inline styles

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +    <div :class="{'line-bottom':isLine}">
冒号后面空格

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +      <div v-if="size=='large'" style="height:24px">
avoid inline styles

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +      <div v-if="size=='large'" style="height:24px">
===

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +      <div class="md-input-item md-field-item-content" :class="[size,align,inputEnv]">
空格

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +    unit: function () {
以前代码里这个方法太蠢了，搜个稍微能看的懂点的

2019-12-16 09:49 UTC, HermannLizard commented on components/md-input/index.vue
> +    handleinfo() {
camelcase

2019-12-16 09:49 UTC, HermannLizard commented on components/textarea/index.vue
> +  name: 'textarea',
为啥要占用原生textarea component name？

2019-12-17 09:41 UTC, HermannLizard reviewed
自研的input和textarea执行以下标准：
1、目录名：input，textarea
2、组件名：md-input, md-textarea
3、打包模块名：input，textarea

2019-12-17 09:41 UTC, HermannLizard commented on components/input-search/index.vue
> +<div :class="[align,align =='center'? 'search-wrapper' : '']">
数组item间空格，三等，二元操作符左右空格

2019-12-17 09:41 UTC, HermannLizard commented on components/input-search/index.vue
> +    <md-icon v-show="isShow" name="search" size="xs" style="position:absolute;left:5px" />
如果行内样式是必要的，请在注释中给出解释；否则请使用class

2019-12-17 09:41 UTC, HermannLizard commented on components/md-input/index.vue
> +      else if (len >= 5 && len <= 12) {
if里都排除len<5，else里不用len >= 5了吧。
这里可以简写：
return len < 5 ? '' : arr[Math.min(len, 12) - 5];

2019-12-17 09:41 UTC, HermannLizard commented on components/md-input/index.vue
> +    console.log(this.inputValue);
console一般不进仓库

2019-12-17 09:42 UTC, HermannLizard reviewed
见上一个commit的comment

2019-12-17 10:29 UTC, taiyang1994 commented on components/input-search/index.vue
> +    ]"
这个不是bool类型，它是三个值，

2019-12-19 11:10 UTC, HermannLizard approved these changes
approve

2019-12-19 11:10 UTC, merged